name: Publish package
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'zulu'
          server-id: github
          server-username: GITHUB_USERNAME
          server-password: GITHUB_PASSWORD
      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          GITHUB_USERNAME: ${{ secrets.GITHUBUSERNAME }}
          GITHUB_PASSWORD: ${{ secrets.GITHUBTOKEN }}